#!/bin/bash
if [[ "$EAS_BUILD_PLATFORM" == "android" ]]; then
  echo "Creating symlinks for libncurses.so.5 and libtinfo.so.5..."
  sudo ln -sf /usr/lib/x86_64-linux-gnu/libncurses.so.6 /usr/lib/x86_64-linux-gnu/libncurses.so.5
  sudo ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
fi